name: schieved
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: 6.2.1
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  firebase_core: 3.1.0
  dio: 5.4.3+1
  flutter_native_splash: 2.4.0
  cloud_firestore: 5.0.1
  shimmer: 3.0.0
  table_calendar: 3.1.2
  smooth_page_indicator: 1.1.0
  percent_indicator: 4.2.3
  get_storage: 2.1.1
  firebase_auth: 5.1.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/illustration/
  uses-material-design: true

