// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDkKk3L0bfexqQTum3fzdIiukwTZMTUNQ',
    appId: '1:429367086897:web:b42035c259fdbd4ac52a10',
    messagingSenderId: '429367086897',
    projectId: 'schieved',
    authDomain: 'schieved.firebaseapp.com',
    storageBucket: 'schieved.appspot.com',
    measurementId: 'G-GD50PZMMS0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCbwvk22kqHYKfBTZ_tCd_y6lE1zgAjY',
    appId: '1:429367086897:ios:292efd67caf54f9ac52a10',
    messagingSenderId: '429367086897',
    projectId: 'schieved',
    storageBucket: 'schieved.appspot.com',
    iosBundleId: 'com.lucid.schieved',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCbwvk22kqHYKfBTZ_tCd_y6lE1zgAjY',
    appId: '1:429367086897:ios:292efd67caf54f9ac52a10',
    messagingSenderId: '429367086897',
    projectId: 'schieved',
    storageBucket: 'schieved.appspot.com',
    iosBundleId: 'com.lucid.schieved',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDkKk3L0bfexqQTum3fzdIiukwTZMTUNQ',
    appId: '1:429367086897:web:8b29a298f9de853dc52a10',
    messagingSenderId: '429367086897',
    projectId: 'schieved',
    authDomain: 'schieved.firebaseapp.com',
    storageBucket: 'schieved.appspot.com',
    measurementId: 'G-XS5NGJGSX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2pWkrKnV_RXmY_iYy-7iDOBYB0QrBxw',
    appId: '1:429367086897:android:23b39de398e7ace0c52a10',
    messagingSenderId: '429367086897',
    projectId: 'schieved',
    storageBucket: 'schieved.appspot.com',
  );

}